version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: debug.Dockerfile
    volumes:
      - ${PWD}:/src-root
    environment:
      RUST_LOG: info
      DATABASE_URL: postgres://demo_user:demo_password@db:5432/demo_db
      JWT_SECRET: ITS A SECRET
      ARGON_SECRET: ITS ANOTHER SECRET
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: demo_db
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
